---
################################################################################
# Handlers for silverblue_printer_config role
################################################################################

- name: restart cups
  systemd:
    name: cups
    state: restarted
