---
################################################################################
# Handlers for silverblue_nightly_reset role
################################################################################

- name: reload systemd
  systemd:
    daemon_reload: yes
