---
################################################################################
# Handlers for ssh_hardening role
################################################################################

- name: Restart SSH
  systemd:
    name: sshd
    state: restarted
