---
################################################################################
# Handlers for ssh_config role
################################################################################

- name: Restart SSH
  systemd:
    name: sshd
    state: restarted
