---
################################################################################
# Ansible Inventory - Development Environment
# Purpose: Dynamic inventory built as VMs are created
################################################################################

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    domain_name: "corp.company.local"

  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.35.20
          ansible_user: root

    workstations:
      hosts:
        ws-admin01:
          ansible_host: 10.0.130.10
          ansible_user: richard
          vm_role: admin_workstation
