---
################################################################################
# Ansible Inventory - Development Environment
# Purpose: Dynamic inventory built as VMs are created
################################################################################

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    domain_name: "corp.company.local"

  children:
    proxmox:
      hosts:
        pve:
          ansible_host: 192.168.35.20
          ansible_user: root

    servers:
      hosts:
        ansible-ctrl:
          ansible_host: 10.0.120.50
          ansible_user: ansible-admin
          vm_role: ansible_control

    sdc01:
      hosts:
        dc01:
          ansible_host: 10.0.120.10
          ansible_user: ansible-admin
          vm_role: primary_dc
    sdc02:
      hosts:
        dc02:
          ansible_host: 10.0.120.11
          ansible_user: ansible-admin
          vm_role: secondary_dc

    workstations:
      hosts:
        ws-admin01:
          ansible_host: 10.0.131.10
          ansible_user: ansible-admin
          vm_role: admin_workstation
        bu-reception01:
          ansible_host: 10.0.130.135
          ansible_user: ansible-admin
          vm_role: admin_workstation
